name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Download Docker container
        run: docker pull devopscloud153/sample-web-app:latest


      - name: Run the new container
        run: docker run -d -p 8080:8080 --name sample-web-app devopscloud153/sample-web-app:latest
