name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Download Docker container
        run: docker pull devopscloud153/sample-web-app:latest

      - name: Stop existing container (if running)
        run: docker stop sample-web-app || true

      - name: Remove existing container (if exists)
        run: docker rm sample-web-app || true

      - name: Run the new container
        run: docker run -d -p 8080:8080 --name sample-web-app devopscloud153/sample-web-app:latest
