name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Download Docker container
        run: docker pull devopscloud153/sample-web-app:latest
        
      - name: Stop existing container (if running)
        run: docker stop sample-web-app 2>$null; $ErrorActionPreference = 'SilentlyContinue'


      - name: Remove existing container (if exists)
        run: docker rm sample-web-app 2>$null; $ErrorActionPreference = 'SilentlyContinue'


      - name: Run the new container
        run: docker run -d -p 8080:3000 --name sample-web-app devopscloud153/sample-web-app:latest

      - name: Log failure
        if: ${{ failure() }}
        run: |
          echo "$(date) - $GITHUB_REPOSITORY" >> log.txt
