name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          
      - name: Build and publish Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t devopscloud153/sample-web-app:${{ github.sha }} .
          docker build -t devopscloud153/sample-web-app:latest .
          docker run -d -p 8080:8080 devopscloud153/sample-web-app:${{ github.sha }}
          docker login --username '$DOCKER_USERNAME' --password-stdin '$DOCKER_PASSWORD'
          docker push devopscloud153/sample-web-app:${{ github.sha }}
          docker push devopscloud153/sample-web-app:latest
